
default_language_version:
    python: python3.6

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: setup.cfg
        language_version: python3
    -   id: end-of-file-fixer
        exclude: setup.cfg
        language_version: python3
    -   id: check-yaml
        language_version: python3
    -   id: debug-statements
        language_version: python3
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    -   id: black
        language_version: python3
        args: ["--target-version", "py36"]
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        language_version: python3
        args: ['--config=setup.cfg']
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
    -   id: reorder-python-imports
        language_version: python3
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
    -   id: pyupgrade
        language_version: python3
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
