
default_language_version:
    python: python3

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args: ['--py38-plus']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: setup.cfg
      - id: end-of-file-fixer
        exclude: setup.cfg
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--target-version", "py38"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.13.0
    hooks:
      - id: reorder-python-imports
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
